# Generated by Django 3.1.6 on 2021-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('c_index', models.CharField(max_length=200, null=True, verbose_name='Index')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
